"""End-to-end: glue-opcode adjustment toggle.

Paths exercised:

- glue off (the default): glue CSVs and the glue markdown report are not
  produced; `new_gas_all_params.csv` still carries a `glue_adjustment`
  column, uniformly zero.
- glue on: every priced spec with a driver fixture is estimated and written,
  the per-test ratio table is written, and a fit whose target opcode is
  contaminated by a priced glue opcode ends up with a strictly positive
  `glue_adjustment` on `new_gas_all_params.csv`.
- glue on with family driver fixtures spanning multiple members
  (DUP1, DUP2, ...): the family is collapsed to a single `DUP` row, not one
  row per member.
- glue on without the required driver fixtures: the pipeline refuses to
  proceed.
- glue on with the *optional* drivers (POP, STOP) absent: the pipeline
  proceeds — those specs are silently skipped.

The expected priced-glue name set is sourced from
`evm_gasfit.glue.required.PRICED_GLUE_SPECS` so the tests track the
implementation without restating the set.
"""

from __future__ import annotations

import logging
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pandas as pd
import pytest
from _data_synth import (
    ClientModel,
    FixtureSpec,
    base_config,
    cross_product_fixtures,
    make_block_limit_fixtures,
    make_glue_driver_fixtures,
    run_pipeline,
    write_standard_inputs,
)


def _active_priced_names() -> set[str]:
    """Canonical names with a driver fixture (POP/STOP excluded)."""
    from evm_gasfit.glue.required import PRICED_GLUE_SPECS

    return {s.name for s in PRICED_GLUE_SPECS if s.test_name is not None}


def _main_fixtures(extra_per_million: dict[str, float] | None = None):
    return make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million=extra_per_million or {},
    )


def test_glue_disabled_skips_files(tmp_path: Path) -> None:
    fixtures = _main_fixtures(extra_per_million={"ISZERO": 500_000})
    models = {"geth": ClientModel(intercept=80.0, slope=1.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path, fixtures=fixtures, models=models, config=base_config(), seed=1
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir)

    for name in (
        "glue_results.csv",
        "glue_opcodes_by_test.csv",
        "glue_opcodes_autogenerated_report.md",
    ):
        assert not (out_dir / name).exists()

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    assert "glue_adjustment" in new_gas_all.columns
    assert (new_gas_all["glue_adjustment"] == 0).all()


def test_glue_enabled_writes_files_and_adjusts_slope(tmp_path: Path) -> None:
    priced_glue = _active_priced_names()

    # ISZERO background contaminates the ADD fit so the adjustment must
    # subtract the glue contribution out. ISZERO is a priced glue opcode
    # *with* a driver fixture, so it ends up with a non-NaN glue runtime
    # the adjuster can apply.
    main_fixtures = _main_fixtures(extra_per_million={"ISZERO": 500_000})
    all_fixtures = main_fixtures + make_glue_driver_fixtures()
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    anchor_rate = 1.0e8

    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True, anchor_rate=anchor_rate),
        seed=3,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    assert (out_dir / "glue_results.csv").exists()
    assert (out_dir / "glue_opcodes_by_test.csv").exists()
    assert (out_dir / "glue_opcodes_autogenerated_report.md").exists()

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    assert {
        "client_name",
        "glue_opcode",
        "nobs",
        "glue_runtime_ms",
        "p_value",
        "rsquared",
    }.issubset(glue_results.columns)
    # Exactly the priced opcodes with a driver appear (POP/STOP excluded).
    assert set(glue_results["glue_opcode"]) == priced_glue
    assert len(glue_results) == len(priced_glue)  # one client → one row per opcode

    glue_by_test = pd.read_csv(out_dir / "glue_opcodes_by_test.csv")
    assert {"test_name", "target_opcode", "glue_opcode", "corr", "ratio"}.issubset(
        glue_by_test.columns
    )

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    add_rows = new_gas_all[new_gas_all["gas_param"] == "OPCODE_ADD"]
    assert len(add_rows) == 1
    add_row = add_rows.iloc[0]

    # ISZERO contaminates the ADD fit at half the target rate, so the
    # adjustment must be strictly positive (negative values are clipped to
    # zero).
    assert float(add_row["glue_adjustment"]) > 0

    # new_gas_decimal = anchor_rate * post-adjustment runtime_ms / 1000.
    expected_decimal = anchor_rate * float(add_row["runtime_ms"]) / 1000.0
    assert float(add_row["new_gas_decimal"]) == pytest.approx(
        expected_decimal, rel=1e-9
    )


def test_glue_family_collapses_to_single_canonical_row(tmp_path: Path) -> None:
    """DUP1..DUP16 driver fixtures collapse to a single `DUP` glue row."""
    fixtures = _main_fixtures() + make_glue_driver_fixtures()
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        seed=11,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    dup_rows = glue_results[glue_results["glue_opcode"] == "DUP"]
    # Exactly one DUP row per client; no DUP1/DUP3/... rows leaked through.
    assert len(dup_rows) == glue_results["client_name"].nunique()
    leaked = [
        op
        for op in glue_results["glue_opcode"].unique()
        if op.startswith("DUP") and op != "DUP"
    ]
    assert leaked == [], f"unexpected per-member DUP rows: {leaked!r}"

    # DUP's recovered slope should match the synthetic model (2e-5).
    dup_slope = float(dup_rows.iloc[0]["glue_runtime_ms"])
    assert dup_slope == pytest.approx(2.0e-5, rel=0.1)


def test_glue_missing_required_test_raises(tmp_path: Path) -> None:
    """Enabling glue without the required driver fixtures must fail."""
    fixtures = _main_fixtures()  # main model only, no glue drivers
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        noise_pct=0.0,
        seed=4,
    )

    # Acceptable for the error to surface anywhere from load up to
    # estimate_glue() — implementations may detect at different stages.
    from evm_gasfit.errors import ConfigError, ModelingError

    with pytest.raises((ConfigError, ModelingError)):
        run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)


def test_glue_works_with_benchmark_sweep_token(tmp_path: Path) -> None:
    """The detector must not depend on a specific scan-axis token name.

    Real EEST fixtures use `benchmark_<N>M` instead of
    `block_limit_million_<N>`. Opcounts are a property of the fixture, so the
    detector correlates over per-fixture rows regardless of which token names
    the scan axis.
    """
    priced_glue = _active_priced_names()

    main_fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million={"ISZERO": 500_000},
        sweep_token_format="benchmark_{n}M",
    )
    all_fixtures = main_fixtures + make_glue_driver_fixtures(
        sweep_token_format="benchmark_{n}M",
    )
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}

    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        seed=7,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    # Sanity-check the new token shape actually landed on the fixture names.
    runtimes = pd.read_csv(runtimes_csv)
    assert runtimes["fixture_name"].str.contains("benchmark_30M").any()
    assert not runtimes["fixture_name"].str.contains("block_limit_million_").any()

    glue_by_test = pd.read_csv(out_dir / "glue_opcodes_by_test.csv")
    # ISZERO is the contaminant we injected — it must show up as detected glue
    # on the ADD test under the new token convention.
    add_glue = glue_by_test[glue_by_test["test_name"] == "test_arithmetic"]
    assert "ISZERO" in set(add_glue["glue_opcode"])

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    assert set(glue_results["glue_opcode"]) == priced_glue


def test_glue_mixed_a_recovers_planted_slope_after_partner_subtraction(
    tmp_path: Path,
) -> None:
    """Mixed-A fits must subtract priced upstream partners on the LHS.

    Plant a real ISZERO contribution into the ADD runtimes; the modelspec
    fit absorbs both costs into target_coef (biased to 2.5e-5), but the
    mixed-A fit subtracts ISZERO using the pure-tier ISZERO coefficient
    and recovers the clean ADD slope (2e-5).
    """
    add_per_count = 2.0e-5
    iszero_per_count = 1.0e-5
    main_fixtures = _main_fixtures(extra_per_million={"ISZERO": 500_000})
    all_fixtures = main_fixtures + make_glue_driver_fixtures()
    models = {
        "geth": ClientModel(
            intercept=50.0,
            slope=0.0,
            glue_coefs={
                "ADD": add_per_count,
                "ISZERO": iszero_per_count,
                # Small non-zero slopes for the rest keep pure/cycle fits
                # well-conditioned (constant-zero counts would skip them).
                "JUMPDEST": 5e-6,
                "SWAP": 5e-6,
                "DUP": 5e-6,
                "PUSH": 5e-6,
                "PUSH0": 5e-6,
                "GAS": 5e-6,
                "MLOAD": 5e-6,
                "STATICCALL": 5e-6,
                "CALLDATASIZE": 5e-6,
            },
        )
    }
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        noise_pct=0.001,
        seed=11,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    iszero_row = glue_results[glue_results["glue_opcode"] == "ISZERO"].iloc[0]
    add_row = glue_results[glue_results["glue_opcode"] == "ADD"].iloc[0]

    assert float(iszero_row["glue_runtime_ms"]) == pytest.approx(
        iszero_per_count, rel=0.05
    )
    assert float(add_row["glue_runtime_ms"]) == pytest.approx(add_per_count, rel=0.05)

    # Sanity contrast: the modelspec target_coef for ADD absorbs both the
    # planted ADD cost AND the ISZERO contribution (no subtraction at the
    # modelspec level), so it sits near 2.5e-5 — visibly biased compared to
    # the mixed-A recovery above.
    results = pd.read_csv(out_dir / "results.csv")
    add_modelspec = results[results["target_opcode"] == "ADD"].iloc[0]
    assert float(add_modelspec["target_coef_runtime_ms"]) == pytest.approx(
        add_per_count + 0.5 * iszero_per_count, rel=0.05
    )


def test_mixed_glue_partner_draws_reach_adjusted_target_interval() -> None:
    """A mixed fit preserves its upstream partner uncertainty downstream."""
    from evm_gasfit.glue.adjust import compute_glue_adjustment
    from evm_gasfit.glue.estimate import _mixed_fit
    from evm_gasfit.glue.required import SPEC_BY_NAME
    from evm_gasfit.modeling.results import NNLSResults

    n_bootstrap = 100
    groups = np.array(["a", "a", "b", "b"])
    mstore_counts = np.array([1.0, 2.0, 1.0, 2.0])
    iszero_counts = np.array([1.0, 4.0, 1.0, 4.0])
    partner_draws = np.column_stack(
        [np.zeros(n_bootstrap), np.tile([1.0, 3.0], n_bootstrap // 2)]
    )
    iszero_fit = NNLSResults(
        X=np.column_stack([np.ones(4), mstore_counts]),
        y=2.0 * mstore_counts,
        y_name="test_runtime_ms",
        coefficients=np.array([0.0, 2.0]),
        bootstrap_coefs=partner_draws,
        feature_names=["const", "ISZERO"],
        residual_norm=0.0,
        groups=groups,
    )
    mixed_slice = pd.DataFrame(
        {
            "fixture_name": [f"fixture_{i}" for i in range(len(groups))],
            "client_name": "geth",
            "test_name": "test_memory_access",
            "param_opcode": "MSTORE",
            "test_runtime_ms": 10.0 + 5.0 * mstore_counts + 2.0 * iszero_counts,
            "MSTORE": mstore_counts,
            "ISZERO": iszero_counts,
            "session_id": groups,
        }
    )
    mixed_slice.attrs["opcode_columns"] = ["MSTORE", "ISZERO"]
    config = SimpleNamespace(
        modeling=SimpleNamespace(
            bootstrap_iterations=n_bootstrap,
            random_seed=7,
        ),
        campaign=SimpleNamespace(session_column="session_id"),
    )
    mstore_fit, unsubscribed = _mixed_fit(
        mixed_slice,
        config,
        "geth",
        SPEC_BY_NAME["MSTORE"],
        {("geth", "ISZERO"): iszero_fit},
        frozenset({"pure"}),
        p_threshold=0.05,
        r2_threshold=0.5,
        eps=0.05,
    )
    assert mstore_fit is not None
    assert unsubscribed == []

    target_fit = NNLSResults(
        X=np.column_stack([np.ones(4), mstore_counts]),
        y=10.0 * mstore_counts,
        y_name="test_runtime_ms",
        coefficients=np.array([0.0, 10.0]),
        bootstrap_coefs=np.column_stack(
            [np.zeros(n_bootstrap), np.full(n_bootstrap, 10.0)]
        ),
        feature_names=["const", "opcount"],
        residual_norm=0.0,
        groups=groups,
    )
    adjusted = compute_glue_adjustment(
        pd.DataFrame(
            [
                {
                    "source_label": "keccak",
                    "test_name": "test_keccak",
                    "target_opcode": "KECCAK256",
                    "client_name": "geth",
                    "target_coef_runtime_ms": 10.0,
                    "target_coef_conf_int_low": 10.0,
                    "target_coef_conf_int_high": 10.0,
                }
            ]
        ),
        pd.DataFrame(
            [
                {
                    "client_name": "geth",
                    "glue_opcode": "MSTORE",
                    "glue_runtime_ms": 5.0,
                    "p_value": 0.01,
                    "rsquared": 1.0,
                    "isolated": True,
                }
            ]
        ),
        pd.DataFrame(
            [
                {
                    "source_label": "keccak",
                    "test_name": "test_keccak",
                    "target_opcode": "KECCAK256",
                    "glue_opcode": "MSTORE",
                    "corr": 1.0,
                    "ratio": 1.0,
                }
            ]
        ),
        p_threshold=0.05,
        r2_threshold=0.5,
        target_fits={("keccak", "test_keccak", "KECCAK256", "geth"): target_fit},
        glue_fits={("geth", "MSTORE"): mstore_fit},
        random_seed=7,
    ).iloc[0]

    assert not bool(adjusted["glue_interval_conditional"])
    assert bool(adjusted["glue_coverage_complete"])
    assert float(adjusted["adjusted_target_coef_conf_int_low"]) == pytest.approx(2.0)
    assert float(adjusted["adjusted_target_coef_conf_int_high"]) == pytest.approx(8.0)


def test_glue_mixed_b_recovers_planted_slope_after_mixed_a_partner(
    tmp_path: Path,
) -> None:
    """Mixed-B fits draw partners from mixed_a too.

    Plant a real MSTORE contribution into the KECCAK256 runtimes plus a
    matching MSTORE driver slice. The mixed-A fit for MSTORE estimates
    its per-count cost; the mixed-B fit for KECCAK256 must then subtract
    it (using the MSTORE coefficient produced earlier in the same pass)
    to recover the clean KECCAK256 slope.
    """
    keccak_per_count = 3.0e-5
    mstore_per_count = 1.5e-5
    iszero_per_count = 1.0e-5

    keccak_fixtures = make_block_limit_fixtures(
        test_file="test_keccak",
        test_name="test_keccak_diff_mem_msg_sizes",
        target_opcode="KECCAK256",
        params={"opcode": "KECCAK256"},
        extra_opcount_per_million={"MSTORE": 500_000},
    )
    mstore_fixtures = make_block_limit_fixtures(
        test_file="test_memory_access",
        test_name="test_memory_access",
        target_opcode="MSTORE",
        params={"opcode": "MSTORE"},
    )
    # Keep the canonical ADD/test_arithmetic happy path so the existing
    # plumbing (default OPCODE_ADD modelspec, glue drivers) is exercised.
    add_main = _main_fixtures(extra_per_million={"ISZERO": 500_000})
    all_fixtures = (
        add_main + keccak_fixtures + mstore_fixtures + make_glue_driver_fixtures()
    )

    models = {
        "geth": ClientModel(
            intercept=50.0,
            slope=0.0,
            glue_coefs={
                "ADD": 1e-5,
                "MSTORE": mstore_per_count,
                "KECCAK256": keccak_per_count,
                "ISZERO": iszero_per_count,
                "JUMPDEST": 5e-6,
                "SWAP": 5e-6,
                "DUP": 5e-6,
                "PUSH": 5e-6,
                "PUSH0": 5e-6,
                "GAS": 5e-6,
                "MLOAD": 5e-6,
                "STATICCALL": 5e-6,
                "CALLDATASIZE": 5e-6,
            },
        )
    }

    cfg = base_config(
        models_custom=[
            {
                "test_name": "test_arithmetic",
                "target_operation": "ADD",
                "model_params": {"target_coef": "OPCODE_ADD"},
            },
            {
                "test_name": "test_memory_access",
                "target_operation": "MSTORE",
                "filter_by": ["opcode_MSTORE-"],
                "model_params": {"target_coef": "OPCODE_MSTORE_BASE"},
            },
            {
                "test_name": "test_keccak_diff_mem_msg_sizes",
                "target_operation": "KECCAK256",
                "model_params": {"target_coef": "OPCODE_KECCAK256_BASE"},
            },
        ],
        glue_enabled=True,
    )

    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=cfg,
        seed=13,
        noise_pct=0.001,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    mstore_row = glue_results[glue_results["glue_opcode"] == "MSTORE"].iloc[0]
    keccak_row = glue_results[glue_results["glue_opcode"] == "KECCAK256"].iloc[0]

    assert float(mstore_row["glue_runtime_ms"]) == pytest.approx(
        mstore_per_count, rel=0.05
    )
    assert float(keccak_row["glue_runtime_ms"]) == pytest.approx(
        keccak_per_count, rel=0.05
    )


def test_glue_mixed_a_does_not_subtract_other_mixed_a_partners(
    tmp_path: Path,
) -> None:
    """The static four-pass order is enforced by ``allowed_partner_tiers``.

    Contaminate the ADD slice with MSTORE counts (a real partner cost). The
    detector will list MSTORE as a partner of ADD, but the mixed-A fit for
    ADD must **not** subtract MSTORE — both are tier ``mixed_a``, and the
    static order requires mixed-A partners come from ``pure ∪ cycle`` only.
    If the tier guard regressed, ADD's mixed-A slope would recover the
    clean 2e-5; with the guard in place it absorbs the MSTORE contamination
    and lands at 2e-5 + 0.5·1.5e-5 = 2.75e-5.
    """
    add_per_count = 2.0e-5
    mstore_per_count = 1.5e-5

    add_contaminated = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million={"MSTORE": 500_000},
    )
    mstore_clean = make_block_limit_fixtures(
        test_file="test_memory_access",
        test_name="test_memory_access",
        target_opcode="MSTORE",
        params={"opcode": "MSTORE"},
    )
    all_fixtures = add_contaminated + mstore_clean + make_glue_driver_fixtures()
    models = {
        "geth": ClientModel(
            intercept=50.0,
            slope=0.0,
            glue_coefs={
                "ADD": add_per_count,
                "MSTORE": mstore_per_count,
                "ISZERO": 1e-5,
                "JUMPDEST": 5e-6,
                "SWAP": 5e-6,
                "DUP": 5e-6,
                "PUSH": 5e-6,
                "PUSH0": 5e-6,
                "GAS": 5e-6,
                "MLOAD": 5e-6,
                "STATICCALL": 5e-6,
                "CALLDATASIZE": 5e-6,
            },
        )
    }
    cfg = base_config(
        models_custom=[
            {
                "test_name": "test_arithmetic",
                "target_operation": "ADD",
                "model_params": {"target_coef": "OPCODE_ADD"},
            },
            {
                "test_name": "test_memory_access",
                "target_operation": "MSTORE",
                "filter_by": ["opcode_MSTORE-"],
                "model_params": {"target_coef": "OPCODE_MSTORE_BASE"},
            },
        ],
        glue_enabled=True,
    )
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=cfg,
        seed=17,
        noise_pct=0.001,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    # The detector still surfaces MSTORE as an ADD partner (the contamination
    # creates a real corr ≈ 1 row); the tier guard is what prevents it from
    # contributing to the mixed-A fit.
    glue_by_test = pd.read_csv(out_dir / "glue_opcodes_by_test.csv")
    add_partners = set(
        glue_by_test.loc[
            (glue_by_test["test_name"] == "test_arithmetic")
            & (glue_by_test["target_opcode"] == "ADD"),
            "glue_opcode",
        ]
    )
    assert "MSTORE" in add_partners

    # ADD's mixed-A slope absorbs the MSTORE contamination because the tier
    # guard blocked the subtraction; the clean value (2e-5) is NOT recovered.
    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    add_row = glue_results[glue_results["glue_opcode"] == "ADD"].iloc[0]
    contaminated_slope = add_per_count + 0.5 * mstore_per_count
    assert float(add_row["glue_runtime_ms"]) == pytest.approx(
        contaminated_slope, rel=0.05
    )


def test_glue_missing_optional_driver_does_not_raise(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """STOP has no driver fixture in any dataset (it halts execution).

    POP gained a straight-line calibration driver and is now required; only
    STOP remains optional. The pipeline must still run; the spec row just
    doesn't appear in `glue_results.csv`.
    """
    all_fixtures = _main_fixtures() + make_glue_driver_fixtures()
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        seed=21,
    )

    with caplog.at_level(logging.WARNING, logger="evm_gasfit"):
        run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    # POP now carries a real driver row; STOP can never have one.
    assert "POP" in set(glue_results["glue_opcode"])
    assert "STOP" not in set(glue_results["glue_opcode"])


def test_glue_adjustment_applies_across_specs_with_disjoint_model_by(
    tmp_path: Path,
) -> None:
    """Two specs with disjoint `model_by` columns must each still get their
    own glue adjustment.

    `_model_by_cols` keys every row on the *union* of every spec's `model_by`
    columns. A spec's own rows carry NaN in every other spec's columns, and
    `NaN == NaN` is `False` in pandas — so as soon as a second spec with a
    non-empty, disjoint `model_by` enters the run, the ratio mask can
    collapse to all-False for every row and `glue_adjustment` stays 0.0
    everywhere. A single spec (or two specs sharing `model_by`) can't catch
    this: the union then equals each spec's own columns and the bug is
    invisible.
    """
    add_fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million={"ISZERO": 500_000},
    )
    sload_fixtures = cross_product_fixtures(
        test_file="test_storage_probe",
        test_name="test_storage_probe",
        param_grid={"slots": ["0", "1"]},
        target_opcode_for="SLOAD",
        extra_opcount_per_million={"GAS": 500_000},
    )
    all_fixtures = add_fixtures + sload_fixtures + make_glue_driver_fixtures()
    models = {"geth": ClientModel(intercept=50.0, slope=2.0e-5)}

    cfg = base_config(
        models_custom=[
            {
                "test_name": "test_arithmetic",
                "target_operation": "ADD",
                "model_by": ["opcode"],
                "model_params": {"target_coef": "OPCODE_ADD"},
            },
            {
                "test_name": "test_storage_probe",
                "target_operation": "SLOAD",
                "model_by": ["slots"],
                "model_params": {"target_coef": "COLD_STORAGE_ACCESS"},
            },
        ],
        glue_enabled=True,
    )
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=cfg,
        seed=29,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    add_row = new_gas_all[new_gas_all["gas_param"] == "OPCODE_ADD"].iloc[0]
    sload_row = new_gas_all[new_gas_all["gas_param"] == "COLD_STORAGE_ACCESS"].iloc[0]

    assert float(add_row["glue_adjustment"]) > 0
    assert float(sload_row["glue_adjustment"]) > 0


def test_glue_keccak_recognizes_sha3_opcount_alias(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Real fixture data names opcode 0x20 `SHA3`; evm-gasfit's canonical
    name is `KECCAK256`. Both the driver fit (`test_keccak_diff_mem_msg_sizes`)
    and any modelspec test that correlates with it must resolve through the
    alias — a raw `SHA3` opcount column must not be treated as a distinct,
    non-priced opcode, and must not make the driver fit see an all-zero count.
    """
    keccak_per_count = 3.0e-5
    block_limits = (30, 60, 90, 120, 150, 180, 210, 240)

    keccak_driver_fixtures = [
        FixtureSpec(
            test_file="test_keccak",
            test_name="test_keccak_diff_mem_msg_sizes",
            params={},
            block_limit_million=bl,
            target_opcode="KECCAK256",
            target_opcount=bl * 2_000_000.0,
            count_source_opcode="SHA3",
            omit_opcode_token=True,
        )
        for bl in block_limits
    ]

    add_fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
    )
    for spec in add_fixtures:
        spec.extra_opcounts["SHA3"] = spec.target_opcount * 0.5

    all_fixtures = add_fixtures + keccak_driver_fixtures + make_glue_driver_fixtures()
    models = {
        "geth": ClientModel(
            intercept=50.0,
            slope=0.0,
            glue_coefs={
                "ADD": 2.0e-5,
                "KECCAK256": keccak_per_count,
                # Small non-zero slopes for the rest keep pure/cycle fits
                # well-conditioned (constant-zero counts would skip them).
                "ISZERO": 5e-6,
                "JUMPDEST": 5e-6,
                "SWAP": 5e-6,
                "DUP": 5e-6,
                "PUSH": 5e-6,
                "PUSH0": 5e-6,
                "GAS": 5e-6,
                "MLOAD": 5e-6,
                "STATICCALL": 5e-6,
                "CALLDATASIZE": 5e-6,
            },
        )
    }
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=all_fixtures,
        models=models,
        config=base_config(glue_enabled=True),
        seed=31,
    )
    with caplog.at_level(logging.WARNING, logger="evm_gasfit"):
        run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir, glue=True)

    non_priced_warnings = [
        r.getMessage()
        for r in caplog.records
        if "non-priced opcode 'SHA3'" in r.getMessage()
    ]
    assert non_priced_warnings == [], f"unexpected warnings: {non_priced_warnings}"

    glue_by_test = pd.read_csv(out_dir / "glue_opcodes_by_test.csv")
    add_glue = glue_by_test[glue_by_test["test_name"] == "test_arithmetic"]
    assert "KECCAK256" in set(add_glue["glue_opcode"])
    assert "SHA3" not in set(add_glue["glue_opcode"])

    glue_results = pd.read_csv(out_dir / "glue_results.csv")
    keccak_row = glue_results[glue_results["glue_opcode"] == "KECCAK256"].iloc[0]
    assert int(keccak_row["nobs"]) > 0
    assert float(keccak_row["glue_runtime_ms"]) == pytest.approx(
        keccak_per_count, rel=0.05
    )
