"""End-to-end: minimal config drives every always-on output artifact.

The smallest meaningful pipeline run:

- one model spec (``test_arithmetic``, target opcode ``ADD``, single fit per client)
- two clients with distinct true slopes
- glue off (default), plots off

Exercises the public Python API and asserts the artifact schemas, the
recovered slopes, the across-client worst-case selection, and the
``anchor_rate * runtime_ms / 1000`` conversion.
"""

from __future__ import annotations

import math
from pathlib import Path

import pandas as pd
import pytest
from _data_synth import (
    NEW_GAS_ALL_PARAMS_COLUMNS,
    NEW_GAS_COLUMNS,
    RESULTS_COLUMNS,
    ClientModel,
    assert_columns,
    base_config,
    make_block_limit_fixtures,
    run_pipeline,
    write_standard_inputs,
)


def test_minimal_pipeline_end_to_end(tmp_path: Path) -> None:
    fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
        extra_opcount_per_million={"POP": 500_000},
    )
    true_slope: dict[str, float] = {"geth": 1.0e-5, "besu": 1.5e-5}
    true_intercept: dict[str, float] = {"geth": 100.0, "besu": 120.0}
    models = {
        client: ClientModel(intercept=true_intercept[client], slope=true_slope[client])
        for client in true_slope
    }
    anchor_rate = 1.0e8

    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models=models,
        config=base_config(anchor_rate=anchor_rate),
        noise_pct=0.005,
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir)

    # ---- always-on artifacts present, optional ones absent --------------
    for name in (
        "results.csv",
        "new_gas.csv",
        "new_gas_all_params.csv",
        "runtime_estimation_autogenerated_report.md",
        "new_gas_proposal.md",
    ):
        assert (out_dir / name).exists()

    for name in (
        "glue_results.csv",
        "glue_opcodes_by_test.csv",
        "glue_opcodes_autogenerated_report.md",
    ):
        assert not (out_dir / name).exists()

    figs_dir = out_dir / "figs"
    if figs_dir.exists():
        assert not any(figs_dir.rglob("*.png"))

    # ---- results.csv schema + slope recovery ----------------------------
    results = pd.read_csv(out_dir / "results.csv")
    assert_columns(results, RESULTS_COLUMNS, "results.csv")
    assert len(results) == 2  # one row per client; no model_by grouping
    assert set(results["client_name"]) == {"geth", "besu"}
    assert set(results["target_opcode"]) == {"ADD"}
    assert set(results["test_name"]) == {"test_arithmetic"}

    for _, row in results.iterrows():
        client = row["client_name"]
        recovered = float(row["target_coef_runtime_ms"])
        expected = true_slope[client]
        assert recovered == pytest.approx(expected, rel=0.05), (
            f"{client}: target_coef_runtime_ms {recovered} not within 5% of {expected}"
        )
        assert float(row["rsquared"]) > 0.95
        assert int(row["nobs"]) == len(fixtures)

    # ---- new_gas_all_params.csv schema ----------------------------------
    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    assert_columns(new_gas_all, NEW_GAS_ALL_PARAMS_COLUMNS, "new_gas_all_params.csv")

    add_rows = new_gas_all[new_gas_all["gas_param"] == "OPCODE_ADD"]
    assert len(add_rows) == 2  # one per client
    assert set(add_rows["client_name"]) == {"geth", "besu"}
    assert (add_rows["test_name"] == "test_arithmetic").all()
    assert (add_rows["target_opcode"] == "ADD").all()
    assert (add_rows["model_coef_name"] == "target_coef").all()
    # Glue off -> adjustment uniformly zero (column present per schema).
    assert (new_gas_all["glue_adjustment"] == 0).all()
    assert set(add_rows["poor_fit"].dropna().unique()).issubset({True, False})

    # ---- new_gas.csv schema + worst-case across clients ----------------
    new_gas = pd.read_csv(out_dir / "new_gas.csv")
    assert_columns(new_gas, NEW_GAS_COLUMNS, "new_gas.csv")
    assert "OPCODE_ADD" in set(new_gas["gas_param"])

    add_row = new_gas[new_gas["gas_param"] == "OPCODE_ADD"].iloc[0]
    # besu (slope 1.5e-5) produces the larger per-opcode runtime, so it wins.
    assert add_row["client_name"] == "besu"
    assert add_row["selected_test"] == "test_arithmetic"
    assert add_row["selected_opcode"] == "ADD"
    assert add_row["selected_model_coef_name"] == "target_coef"
    assert float(add_row["glue_adjustment"]) == 0.0

    besu_add = add_rows[add_rows["client_name"] == "besu"].iloc[0]
    for col in ("runtime_ms", "conf_int_low", "conf_int_high", "new_gas_decimal"):
        assert float(add_row[col]) == pytest.approx(float(besu_add[col]), rel=1e-12)
    assert int(add_row["new_gas_rounded"]) == int(besu_add["new_gas_rounded"])

    # ---- anchor_rate * runtime_ms / 1000 + ceil rounding ----------------
    expected_decimal = anchor_rate * float(add_row["runtime_ms"]) / 1000.0
    assert float(add_row["new_gas_decimal"]) == pytest.approx(
        expected_decimal, rel=1e-9
    )
    assert int(add_row["new_gas_rounded"]) == math.ceil(
        float(add_row["new_gas_decimal"])
    )


def test_prague_current_gas_comparison_end_to_end(tmp_path: Path) -> None:
    """A Prague run compares measurements against Prague's fork baseline."""
    fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
    )
    config = base_config(anchor_rate=1.0e8, clients=("geth",))
    config["gas_costs"]["fork"] = "prague"
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models={"geth": ClientModel(intercept=100.0, slope=1.0e-5)},
        config=config,
    )

    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir)

    comparison = pd.read_csv(out_dir / "compute_gas_comparison.csv")
    add_row = comparison[comparison["gas_param"] == "OPCODE_ADD"].iloc[0]
    assert int(add_row["current_gas"]) == 3
    assert add_row["current_gas_source"] == "fork"
