"""End-to-end: specs that collide on (test_name, target, model_by).

Two specs can share ``test_name`` + target selection + ``model_by`` shape and
differ only in ``filter_by`` (the shipped catalog does exactly this with
``cold_account_nocode_access`` / ``cold_account_code_access``). The aggregator
routes each ``results.csv`` row back to the exact spec that produced it via the
``source_label`` provenance column, so neither spec expands the other's fit —
no duplicate rows on ``new_gas_all_params.csv``, no cross-contamination.

A byte-identical spec listed twice is always a mistake and is rejected at
config-load time.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest
from _data_synth import (
    ClientModel,
    base_config,
    cross_product_fixtures,
    run_pipeline,
    write_config_yaml,
    write_standard_inputs,
)


def test_filter_by_only_collision_does_not_duplicate_or_contaminate(
    tmp_path: Path,
) -> None:
    # One test slice, target BALANCE, three cache strategies. The two specs
    # below partition the strategies by ``filter_by`` with an overlap on
    # NO_CACHE, mirroring the catalog's nocode/code account-access pair.
    fixtures = cross_product_fixtures(
        test_file="test_account_access",
        test_name="test_account_access",
        param_grid={"cache_strategy": ["NO_CACHE", "HOT", "COLD"]},
        target_opcode_for="BALANCE",
        target_opcount_per_million=800_000,
        extra_opcount_per_million={"POP": 400_000},
    )
    models = {
        "geth": ClientModel(intercept=80.0, slope=1.2e-5),
        "besu": ClientModel(intercept=110.0, slope=1.8e-5),
    }
    config = base_config(
        models_custom=[
            {
                "test_name": "test_account_access",
                "target_operation": "BALANCE",
                "model_by": "cache_strategy",
                "filter_by": ["!HOT"],
                "model_params": {"target_coef": "GAS_ACCESS"},
            },
            {
                "test_name": "test_account_access",
                "target_operation": "BALANCE",
                "model_by": "cache_strategy",
                "filter_by": ["!COLD"],
                "model_params": {"target_coef": "GAS_ACCESS"},
            },
        ],
        new_params={"GAS_ACCESS": None},
    )
    config_yaml, runtimes_csv, opcounts_json, out_dir = write_standard_inputs(
        tmp_path, fixtures=fixtures, models=models, config=config, seed=7
    )
    run_pipeline(config_yaml, runtimes_csv, opcounts_json, out_dir)

    new_gas_all = pd.read_csv(out_dir / "new_gas_all_params.csv")
    gas_rows = new_gas_all[new_gas_all["gas_param"] == "GAS_ACCESS"]

    # Provenance column distinguishes the two specs.
    assert set(gas_rows["source_label"]) == {
        "models.custom[0]",
        "models.custom[1]",
    }

    # Each spec only owns the cache strategies its own ``filter_by`` keeps:
    #   spec 0 (!HOT)  -> NO_CACHE, COLD
    #   spec 1 (!COLD) -> NO_CACHE, HOT
    # No row is contaminated with a strategy the producing spec filtered out.
    owned = {
        "models.custom[0]": {"NO_CACHE", "COLD"},
        "models.custom[1]": {"NO_CACHE", "HOT"},
    }
    for label, strategies in owned.items():
        sub = gas_rows[gas_rows["source_label"] == label]
        # 2 strategies × 2 clients = 4 rows per spec.
        assert len(sub) == 4
        assert set(sub["param_cache_strategy"]) == strategies

    # No row is duplicated on the full identity key (which now includes the
    # producing spec).
    key = [
        "gas_param",
        "client_name",
        "param_cache_strategy",
        "test_name",
        "target_opcode",
        "model_coef_name",
        "source_label",
    ]
    assert not gas_rows.duplicated(subset=key).any()

    # Exactly one winner per (gas_param, client): the across-strategy worst case.
    winners = gas_rows[gas_rows["is_winner"].eq(True)]
    assert len(winners) == 2
    assert set(winners["client_name"]) == {"geth", "besu"}

    # The runtime report keeps the two specs' fits distinct rather than letting
    # one overwrite the other: NO_CACHE is produced by both, so its block is
    # disambiguated by source_label.
    report = (out_dir / "runtime_estimation_autogenerated_report.md").read_text()
    assert "— combo `NO_CACHE` — `models.custom[0]`" in report
    assert "— combo `NO_CACHE` — `models.custom[1]`" in report


def test_byte_identical_specs_are_a_config_error(tmp_path: Path) -> None:
    spec = {
        "test_name": "test_arithmetic",
        "target_operation": "ADD",
        "model_params": {"target_coef": "OPCODE_ADD"},
    }
    config = base_config(models_custom=[dict(spec), dict(spec)])
    config_yaml = tmp_path / "config.yaml"
    write_config_yaml(config_yaml, {**config, "clients": ["geth"]})

    from evm_gasfit import GasFit
    from evm_gasfit.errors import ConfigError

    with pytest.raises(ConfigError, match=r"duplicate model spec"):
        GasFit.from_config(config_yaml)
