"""End-to-end: the `evm-gasfit run` CLI.

The CLI is purely I/O paths plus `--out` — every behavioral knob lives in
the YAML config. These tests pin the three documented exit codes:

- 0: valid invocation populates `--out` with the always-on artifacts.
- 1: config or input error (missing file; unknown `gas_costs.overrides` key).
- 2: modeling error — every model spec was skipped, so no rows were produced.

Invocation prefers the installed `evm-gasfit` console script and falls back
to `python -m evm_gasfit.cli` so the suite works pre-install.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pandas as pd
from _data_synth import (
    ClientModel,
    base_config,
    make_block_limit_fixtures,
    write_standard_inputs,
)


def _invoke_cli(args: list[str]) -> subprocess.CompletedProcess[str]:
    if shutil.which("evm-gasfit"):
        cmd = ["evm-gasfit", *args]
    else:
        cmd = [sys.executable, "-m", "evm_gasfit.cli", *args]
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def _prep(
    tmp_path: Path, *, config: dict[str, Any] | None = None
) -> tuple[Path, Path, Path, Path]:
    fixtures = make_block_limit_fixtures(
        test_file="test_arithmetic",
        test_name="test_arithmetic",
        target_opcode="ADD",
        params={"opcode": "ADD"},
    )
    models = {"geth": ClientModel(intercept=80.0, slope=1.0e-5)}
    return write_standard_inputs(
        tmp_path,
        fixtures=fixtures,
        models=models,
        config=config if config is not None else base_config(),
        noise_pct=0.002,
    )


def _cli_args(config: Path, runtimes: Path, opcounts: Path, out: Path) -> list[str]:
    return [
        "run",
        "--config",
        str(config),
        "--runtimes",
        str(runtimes),
        "--opcounts",
        str(opcounts),
        "--out",
        str(out),
    ]


def test_cli_run_succeeds_and_populates_out(tmp_path: Path) -> None:
    config_yaml, runtimes_csv, opcounts_json, out_dir = _prep(tmp_path)

    result = _invoke_cli(_cli_args(config_yaml, runtimes_csv, opcounts_json, out_dir))

    assert result.returncode == 0, (
        f"CLI exited with {result.returncode}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )

    for name in (
        "results.csv",
        "new_gas.csv",
        "new_gas_all_params.csv",
        "runtime_estimation_autogenerated_report.md",
        "new_gas_proposal.md",
        "meta.json",
    ):
        assert (out_dir / name).exists(), f"missing always-on artifact: {name}"

    results = pd.read_csv(out_dir / "results.csv")
    assert len(results) >= 1
    assert {"target_coef_runtime_ms", "intercept_runtime_ms"}.issubset(results.columns)

    new_gas = pd.read_csv(out_dir / "new_gas.csv")
    assert {"new_gas_decimal", "new_gas_rounded"}.issubset(new_gas.columns)

    meta = json.loads((out_dir / "meta.json").read_text())
    # All synthesized fixtures are present in both inputs, so nothing was dropped.
    assert meta["fixtures"]["dropped"] == 0
    assert meta["dropped_fixtures"] == []
    assert meta["fixtures"]["matched"] == meta["fixtures"]["in_runtimes"]
    assert meta["fixtures"]["matched"] == meta["fixtures"]["in_opcounts"]
    # Clean synth run — no fit/glue/fixture warnings expected.
    assert meta["warnings"] == []


def test_cli_missing_input_returns_exit_code_1(tmp_path: Path) -> None:
    config_yaml, _, opcounts_json, out_dir = _prep(tmp_path)
    nonexistent = tmp_path / "nope.csv"

    result = _invoke_cli(_cli_args(config_yaml, nonexistent, opcounts_json, out_dir))

    assert result.returncode == 1, (
        f"expected exit 1 for missing input, got {result.returncode}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def test_cli_unknown_override_key_returns_exit_code_1(tmp_path: Path) -> None:
    # An `overrides` key that isn't a raw fork field is a hard config error
    # — you cannot patch a non-existent field on the fork's GasCosts.
    config = base_config(overrides={"NOT_A_REAL_FIELD": 123})
    config_yaml, runtimes_csv, opcounts_json, out_dir = _prep(tmp_path, config=config)

    result = _invoke_cli(_cli_args(config_yaml, runtimes_csv, opcounts_json, out_dir))

    assert result.returncode == 1, (
        f"expected exit 1 for unknown override key, got {result.returncode}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def test_cli_no_fits_produces_modeling_error_exit_2(tmp_path: Path) -> None:
    # `filter_by` matches no fixtures, so the only spec is skipped — zero
    # rows in results.csv triggers ModelingError → exit 2.
    config = base_config()
    config["models"]["custom"][0]["filter_by"] = ["opcode_NEVERMATCHES"]
    config_yaml, runtimes_csv, opcounts_json, out_dir = _prep(tmp_path, config=config)

    result = _invoke_cli(_cli_args(config_yaml, runtimes_csv, opcounts_json, out_dir))

    assert result.returncode == 2, (
        f"expected exit 2 for empty modeling output, got {result.returncode}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
